version: '3'
services:
  web:
    container_name: odoo
    image: odoo:16
    build: ./
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
    environment:
      - VIRTUAL_HOST=odoo15.marlonfalcon.com
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    restart: always
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
